export const SET_PLACES_ACTION = "SET_PLACES_ACTION";
export const SET_FILENAME_ACTION = "SET_FILENAME_ACTION";
export const SET_FILTER_STRING_ACTION = "SET_FILTER_STRING_ACTION";
export const SET_EDITED_PLACE_ACTION = "SET_EDITED_PLACE_ACTION";
export const SAVE_UPDATED_PLACE_ACTION = "SAVE_UPDATED_PLACE_ACTION";
